title: Technical Documentation
description:  Technical documentation for a reusable, open-source architecture delivering digitally sovereign GenAI solutions in the danish public sector.
theme: just-the-docs

aux_links:
  Project site: https://www.os2.eu/os2ai
